// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpO7Y1BbhKKYQeTewx-ipWH8traOSrHbQ',
    appId: '1:418755028159:web:bd3167e3d3ccf8725b520a',
    messagingSenderId: '418755028159',
    projectId: 'ember-test-88722',
    authDomain: 'ember-test-88722.firebaseapp.com',
    storageBucket: 'ember-test-88722.appspot.com',
    measurementId: 'G-N0PMN4190D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo7WPiNfe48tqTcTOCVKG7KbJd1c6lFBg',
    appId: '1:418755028159:android:ed0eceaf3b71f5555b520a',
    messagingSenderId: '418755028159',
    projectId: 'ember-test-88722',
    storageBucket: 'ember-test-88722.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXYea1dN4RMCjgPvkh9WuR32FCDi6ofco',
    appId: '1:418755028159:ios:31667b3e5a3176425b520a',
    messagingSenderId: '418755028159',
    projectId: 'ember-test-88722',
    storageBucket: 'ember-test-88722.appspot.com',
    iosClientId: '418755028159-pjnm9hhd2udj04fm82i4um9mkuga1e71.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXYea1dN4RMCjgPvkh9WuR32FCDi6ofco',
    appId: '1:418755028159:ios:31667b3e5a3176425b520a',
    messagingSenderId: '418755028159',
    projectId: 'ember-test-88722',
    storageBucket: 'ember-test-88722.appspot.com',
    iosClientId: '418755028159-pjnm9hhd2udj04fm82i4um9mkuga1e71.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationTest',
  );
}
